version: "3.2"
services:
  flask:
    build: './app/flask/'
    volumes:
      - ./app/flask/:/app
    ports:
      - "##PORT##:80"
    environment:
        - FLASK_APP=app/main.py
        - FLASK_DEBUG=1
        - 'RUN=flask run --host=0.0.0.0 --port=80'
